### ISSUE TITLE
Add support with Modular machinery addons

### ISSUE THREAD

**Issue by infiner5** [NovaEngineering-Source/ModularMachinery-Community-Edition#100]
Like the title says, it would be pretty nice if modular machinery addons such as modular controlers and modular augmentation etc. could be used along with modular machinery CE. It could be in a seperate mod that provides the classes that the MM addons depend on rather than intergrating them directly in MM CE

**Comment by KasumiNova** [comment]
Sorry, but most of the functionality has been rewritten or enhanced in MMCE, and it may be very difficult to make the addon mod compatible.
