### ISSUE TITLE
Crashes without AE2

### ISSUE THREAD

**Issue by roidrole** [NovaEngineering-Source/ModularMachinery-Community-Edition#101]
I tried booting up the game with the following mods : 
- Minecraft 1.12.2
- Forge 14.23.5.2859
- MixinBooter 9.1
- Modular Machinery : Community Edition 2.0.0-pre6
- CraftTweaker2 1.12-4.1.20.698

Upon loading the game, a crash report ([log](https://mclo.gs/rCNxnnn))
Once I installed AE2 UEL: Extended rv6-stable-7, the crash was gone

**Comment by KasumiNova** [comment]
Same with #102
