### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by dercodeKoenig** [NovaEngineering-Source/ModularMachinery-Community-Edition#102]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.1.1-1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MixinLoader (water-erosion-1.12.2-forge-1.1.1-beta1-full.jar)
  MixinBooter (!mixinbooter-8.8.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  MMCEEarlyMixinLoader (ModularMachinery-CE-2.0.0-pre6.jar)
  ierenderfix (ierenderfix-1.0.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/12/24 1:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modular Machinery: Community Edition (modularmachinery)
Caused by: java.lang.NoClassDefFoundError: github/kasuminova/mmce/common/tile/MEPatternProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
	at hellfirepvp.modularmachinery.ModularMachinery.preInit(ModularMachinery.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: github.kasuminova.mmce.common.tile.MEPatternProvider
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: appeng/api/networking/crafting/ICraftingProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 49 more
Caused by: java.lang.ClassNotFoundException: appeng.api.networking.crafting.ICraftingProvider
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more
Caused by: java.lang.NullPointerException

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1128616976 bytes (1076 MB) / 2854748160 bytes (2722 MB) up to 5667028992 bytes (5404 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6080m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 92 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                         | Source                                          | Signature                                |
	|:----- |:--------------------------- |:------------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2                          | minecraft.jar                                   | None                                     |
	| LCH   | mcp                         | 9.42                            | minecraft.jar                                   | None                                     |
	| LCH   | FML                         | 8.0.99.99                       | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                       | 14.23.5.2859                    | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy           | 1.0.0                           | minecraft.jar                                   | None                                     |
	| LCH   | itemphysic                  | 1.4.0                           | minecraft.jar                                   | None                                     |
	| LCH   | mixinbooter                 | 8.8                             | minecraft.jar                                   | None                                     |
	| LCH   | crafttweaker                | 4.1.20                          | CraftTweaker2-1.12-4.1.20.700.jar               | None                                     |
	| LCH   | mtlib                       | 3.0.7                           | MTLib-3.0.7.jar                                 | None                                     |
	| LCH   | modtweaker                  | 4.0.19                          | modtweaker-4.0.20.11.jar                        | None                                     |
	| LCH   | jei                         | 4.16.1.301                      | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCH   | buildcraftlib               | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftcore              | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftbuilders          | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftenergy            | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftfactory           | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | railcraft                   | 12.0.0                          | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | mantle                      | 1.12-1.3.3.55                   | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCH   | quark                       | r1.6-179                        | Quark-r1.6-179.jar                              | None                                     |
	| LCH   | twilightforest              | 3.11.1021                       | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCH   | tconstruct                  | 1.12.2-2.13.0.183               | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCH   | immersiveengineering        | 0.12-98                         | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCH   | libvulpes                   | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | ARLib-19062024.jar                              | None                                     |
	| LCH   | advancedrocketry            | 2.1.1-1                         | AdvancedRocketry-1.12.2-2.1.1-1.jar             | None                                     |
	| LCH   | alternatingflux             | 0.12.2-2                        | alternatingflux-0.12.2-2.jar                    | None                                     |
	| LCH   | ambientenvironment          | 1.0.1                           | AmbientEnvironment-1.0.2.jar                    | None                                     |
	| LCH   | appleskin                   | 1.0.14                          | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
	| LCH   | autoreglib                  | 1.3-32                          | AutoRegLib-1.3-32.jar                           | None                                     |
	| LCH   | base                        | 3.14.0                          | base-1.12.2-3.14.0.jar                          | None                                     |
	| LCH   | bettercaves                 | 1.12.2                          | bettercaves-1.12.2-2.0.4.jar                    | None                                     |
	| LCH   | bettermineshafts            | 1.12.2-2.2.1                    | BetterMineshaftsForge-1.12.2-2.2.1.jar          | None                                     |
	| LCH   | betterquesting              | 3.5.329                         | BetterQuesting-3.5.329.jar                      | None                                     |
	| LCH   | biomesoplenty               | 7.0.1.2445                      | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
	| LCH   | buildcrafttransport         | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftsilicon           | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftcompat            | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | buildcraftrobotics          | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCH   | carryon                     | 1.12.3                          | carryon-1.12.2-1.12.7.23.jar                    | None                                     |
	| LCH   | codechickenlib              | 3.2.3.358                       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks               | 2.4.2.74                        | ChickenChunks-1.12.2-2.4.2.74-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | contenttweaker              | 1.12.2-4.10.0                   | ContentTweaker-1.12.2-4.10.0.jar                | None                                     |
	| LCH   | conarm                      | 1.2.5.10                        | conarm-1.12.2-1.2.5.10.jar                      | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCH   | ctgui                       | 1.0.0                           | CraftTweaker2-1.12-4.1.20.700.jar               | None                                     |
	| LCH   | crafttweakerjei             | 2.0.3                           | CraftTweaker2-1.12-4.1.20.700.jar               | None                                     |
	| LCH   | creativecore                | 1.10.0                          | CreativeCore_v1.10.71_mc1.12.2.jar              | None                                     |
	| LCH   | dynamiclights               | 1.4.9                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_onfire        | 1.0.7                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_creepers      | 1.0.6                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_dropitems     | 1.1.0                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_entityclasses | 1.0.1                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_mobequipment  | 1.1.0                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_flamearrows   | 1.0.1                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_floodlights   | 1.0.3                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_otherplayers  | 1.0.9                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | dynamiclights_theplayer     | 1.1.3                           | DynamicLights-1.12.2.jar                        | None                                     |
	| LCH   | orelib                      | 3.6.0.1                         | OreLib-1.12.2-3.6.0.1.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                   | 3.6.1.0                         | DynamicSurroundings-1.12.2-3.6.1.0.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictrees                | 1.12.2-0.9.29                   | DynamicTrees-1.12.2-0.9.29.jar                  | None                                     |
	| LCH   | dynamictreesbop             | 1.12.2-9999.9999.9999z          | DynamicTreesBOP-1.12.2-1.5.2.jar                | None                                     |
	| LCH   | dynamictreesquark           | 1.12.2-1.0.6                    | DynamicTreesQuark-1.12.2-1.0.6.jar              | None                                     |
	| LCH   | thebetweenlands             | 3.9.6                           | TheBetweenlands-3.9.6-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCH   | dynamictreestbl             | 1.0.3                           | DynamicTreesTheBetweenlands-1.12.2-1.0.3.jar    | None                                     |
	| LCH   | energyconverters            | 1.3.7.30                        | energyconverters_1.12.2-1.3.7.30.jar            | None                                     |
	| LCH   | fbp                         | 2.4.1                           | FancyBlockParticles-1.12.x-2.4.1.jar            | None                                     |
	| LCH   | finite_water                | 1.0                             | finite_water-1.0.jar                            | None                                     |
	| LCH   | ftbbackups                  | 1.1.0.1                         | FTBBackups-1.1.0.1.jar                          | None                                     |
	| LCH   | gravestone                  | 1.10.3                          | gravestone-1.10.3.jar                           | None                                     |
	| LCH   | waila                       | 1.8.26                          | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCH   | immersivepetroleum          | 1.1.10                          | immersivepetroleum-1.12.2-1.1.10.jar            | None                                     |
	| LCH   | jeiintegration              | 1.6.0                           | jeiintegration_1.12.2-1.6.0.jar                 | None                                     |
	| LCH   | journeymap                  | 1.12.2-5.7.1p2                  | journeymap-1.12.2-5.7.1p2.jar                   | None                                     |
	| LCH   | lostcities                  | 2.0.22                          | lostcities-1.12-2.0.22.jar                      | None                                     |
	| LCH   | immersivetech               | 1.9.102                         | MCTImmersiveTechnology-1.12.2-1.9.102.jar       | None                                     |
	| LCH   | medivalmusic                | 1.12.2-1.1                      | medivalmusic-1.1.jar                            | None                                     |
	| LCE   | modularmachinery            | 1.11.1                          | ModularMachinery-CE-2.0.0-pre6.jar              | None                                     |
	| LC    | mysticalworld               | 1.12.2-1.11.0                   | mysticalworld-1.12.2-1.11.0.jar                 | None                                     |
	| LC    | naturescompass              | 1.8.5                           | NaturesCompass-1.12.2-1.8.5.jar                 | None                                     |
	| LC    | patchouli                   | 1.0-23.6                        | Patchouli-1.0-23.6.jar                          | None                                     |
	| LC    | questbook                   | 3.1.1-1.12                      | questbook-3.1.1-1.12.jar                        | None                                     |
	| LC    | refinedstorage              | 1.6.16                          | refinedstorage-1.6.16.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | additionalstructures        | 2.5.0                           | Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar  | None                                     |
	| LC    | savemystronghold            | 1.12.2-1.0.0                    | savemystronghold-1.12.2-1.0.0.jar               | None                                     |
	| LC    | sit                         | v1.3                            | sit-1.12.2-v1.3.jar                             | None                                     |
	| LC    | bq_standard                 | 3.4.173                         | StandardExpansion-3.4.173.jar                   | None                                     |
	| LC    | tcomplement                 | 1.12.2-0.4.3                    | TinkersComplement-1.12.2-0.4.3.jar              | None                                     |
	| LC    | tinkertoolleveling          | 1.12.2-1.1.0.DEV.b23e769        | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LC    | water-erosion               | 1.1.1-beta1                     | water-erosion-1.12.2-forge-1.1.1-beta1-full.jar | None                                     |
	| LC    | waystones                   | 4.1.0                           | Waystones_1.12.2-4.1.0.jar                      | None                                     |
	| LC    | structurize                 | 1.12.2-0.10.277-RELEASE         | structurize-1.12.2-0.10.277-RELEASE.jar         | None                                     |
	| LC    | minecolonies                | 1.12.2-0.11.841-ALPHA           | minecolonies-1.12.2-0.11.841-BETA-universal.jar | None                                     |
	| LC    | mysticallib                 | 1.12.2-1.13.0                   | mysticallib-1.12.2-1.13.0.jar                   | None                                     |
	| UD    | advancedrocketrycore        | 1                               | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.1.1-1.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
MixinLoader (water-erosion-1.12.2-forge-1.1.1-beta1-full.jar)
  
MixinBooter (!mixinbooter-8.8.jar)
  
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
MMCEEarlyMixinLoader (ModularMachinery-CE-2.0.0-pre6.jar)
  
ierenderfix (ierenderfix-1.0.jar)
  com.ierenderfix.MyClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.23' Renderer: 'NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

**Comment by KasumiNova** [comment]
Already fix is github version
