### ISSUE TITLE
Bug of hiding the controller block with the GeckoLib model

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#106]
MMCE Version: 2.0.0-pre7

The essence of the problem lies in the periodic appearance of the controller block model when rendering the GeckoLib model.
The problem arises when the mechanism executes the recipe and we re-enter the world. If the controller is broken and put back, the problem disappears before the next re-entry into the world. 

I also noticed this problem when the active recipe for energy generation stops when the energy output hatch is full, but this does not always appear.

Video showing the bug:

https://github.com/user-attachments/assets/012dbdff-de36-4e44-a9a9-3d2144612db1

**Comment by TheTzdDark** [comment]
Perhaps this will help to identify the problem more accurately. The controller block model is displayed at the beginning/end of the recipe

**Comment by KasumiNova** [comment]
fixed in pre8.
