### ISSUE TITLE
The controller block is never rendered

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#108]
After fixing this problem(https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/issues/106), the controller block is never displayed again, even when the structure is not formed, or does not have a GeckoLib model at all

![image](https://github.com/user-attachments/assets/230cf93d-e244-47a6-a92f-041f6ae0de9c)

**Comment by KasumiNova** [comment]
🤔

**Comment by KasumiNova** [comment]
provide game log?
