### ISSUE TITLE
A preview of the machine with Lumenazed

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#111]
When viewing the machine assembled with the GeckoLib model, the parts that are marked with the bloom effect are not displayed:

JEI:
![image](https://github.com/user-attachments/assets/d4c93d8e-2223-4660-a723-58e26a0501e1)

In the world:
![image](https://github.com/user-attachments/assets/ba1d9147-6184-40ca-a1d3-68a1003ffae5)

**Comment by KasumiNova** [comment]
quite beautiful...

**Comment by KasumiNova** [comment]
After testing, the bloom cube is displayed properly, but some parts may be covered by other cubes due to z-fighting issues.

**Comment by TheTzdDark** [comment]
Yes, I know that there are parts in my model that cover others. But the fact is that when I put a semi-transparent render on intersecting cubes, I get this result:
![image](https://github.com/user-attachments/assets/a395e940-c435-4ed1-87ab-21912bcbe4e2)
![image](https://github.com/user-attachments/assets/54fc955f-2e86-4192-90b1-eca2e44b29fb)

**Comment by KasumiNova** [comment]
🤔

**Comment by KasumiNova** [comment]
A test fix was pushed on the latest github release to try and see if the issue is still there.

**Comment by TheTzdDark** [comment]
The problem still remains :(

**Comment by TheTzdDark** [comment]
Yes, of course
[auto_fusion.zip](https://github.com/user-attachments/files/16442955/auto_fusion.zip)

**Comment by KasumiNova** [comment]
Try to levitate the bloom part of the model appropriately...
Like +0.05 ~ +0.1.
Also there should be no need for the transparent tag.
