### ISSUE TITLE
NTB (!()

### ISSUE THREAD

**Issue by RenanVieira88** [NovaEngineering-Source/ModularMachinery-Community-Edition#38]
Good day for you!

Has a way to make on machine parts NTB "Different off"?:

![image](https://github.com/KasumiNova/ModularMachinery-Community-Edition/assets/24437327/2c221fc8-faee-4b21-b694-8be70d37d813)

**Comment by KasumiNova** [comment]
Will it work to remove it?

**Comment by RenanVieira88** [comment]
If I remove the entire line, its work with or without NTB

My idea is:

        {
            "x": 3,
            "y": 1,
            "z": -1,
            "nbt": " NOT EQUAL TO :"{"torque":"0.0f"}},
            "elements": [
                "immersiveintelligence:mechanical_device@0"
                
                Then the machine are monted
                I've used Transmission Box to Simulate a Windmill Rotor with MMC but its only be work, if windmill is operational.
                The problem here is Windmill send 20.0f Torque and Watermill 24.0f
                If the criteria are NOT EQUAL TO 0 its work on 2 cenarios 
                
                Sorry for my bad english

**Comment by KasumiNova** [comment]
You can use ZenScript to add relevant determinations after JSON registers the relevant machinery and structures, which might work for your needs.

[Code](https://pastebin.mozilla.org/1u2FjyAy)

**Comment by RenanVieira88** [comment]
I've never used Zs to make machines, only to make recipes.

I will try make this, tnks KasumiNova :)

**Comment by KasumiNova** [comment]
Due to the length of time this issue has gone unanswered, it is now closed, please re-open if you have any questions.
