### ISSUE TITLE
Modular Machinery machine controller not generating

### ISSUE THREAD

**Issue by Blocky106** [NovaEngineering-Source/ModularMachinery-Community-Edition#45]
as mentioned in the title, some controllers are not generating. the multiblock is inside of the game, but the controller not, upon trying to add a recipe for the controller, it says "item not found or something along those lines"

**Comment by KasumiNova** [comment]
Sorry, I still don't quite understand what you mean.
Do you mean that machine controller were not added to the game?

**Comment by Blocky106** [comment]
yes

**Comment by Blocky106** [comment]
i have 22 machines and 19 of these have controllers
but the others dont

**Comment by Blocky106** [comment]
the multiblocks are displaying jei
