### ISSUE TITLE
Machines not starting

### ISSUE THREAD

**Issue by toawa** [NovaEngineering-Source/ModularMachinery-Community-Edition#48]
Mod version: ModularMachinery-CE-1.12.2-1.11.1-r47

This is in particular reference to the modpack GregTech Beyond 0.42: https://www.curseforge.com/minecraft/modpacks/gregtech-beyond

There seems to be a bug with multi-block machines; I've talked with the modpack author and they suggested I file an issue here.

Several (but not all) of the multi-block machines defined in this modpack are failing to start when all of the ingredients for a recipe are available to it.  When looking at the controller block, it will correctly identify the structure that it is meant to be (IE, "Vacuum Distillery", "Water Tower", etc), however the machine status will just stay on "Idle", despite the inputs being present, output space being available, energy being available, etc.

The machines worked in a previous modpack version (0.40), which used a different version (ModularMachinery-CE-fork).

Some multi-block machines ("Vacuum Furnace") do still work properly after constructed.  Machines that were constructed under the old modpack ("Water Tower") and them upgraded to the new modpack, continued to work (until I destroyed and replaced the controller block, after which it would not start and remained on "Idle").

The machine's recipes seem to be properly defined (they show up in HEI).  I've only tested a limited number of machines (Water Tower, Vacuum Furnace, Vacuum Distiller, Vis Breaker). Only the Vacuum Furnace works. Water Tower has no inputs (other than energy), Vacuum Distiller and Vis Breaker have fluid inputs only.  Vacuum Furnace has item inputs only. (I wondered if that was the reason, no item inputs, but I tried adding item inputs to the Vacuum Distiller and it didn't change anything.)

**Comment by KasumiNova** [comment]
Can you provide a copy of the latest game log?
Also does the problem continue after trying to update to R48?

**Comment by toawa** [comment]
Updating to r48 appears to have fixed it.
