### ISSUE TITLE
IC2 Incompatability

### ISSUE THREAD

**Issue by NordicGamerFE** [NovaEngineering-Source/ModularMachinery-Community-Edition#49]
Hey, I recently switched from MM to MMCE and noticed that all my machines that contain ic2 blocks have stopped working and I can not get it working. I am using the newest version of IC2 and MMCE as of 27.09.23.

**Comment by KasumiNova** [comment]
Game log?

**Comment by NordicGamerFE** [comment]
[latest.log](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/12735298/latest.log)
[debug.log](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/12735299/debug.log)

**Comment by KasumiNova** [comment]
Sorry, but I can't get useful evidence from the logs to conclude that it's an MMCE issue, it's possible that other mods are breaking the relevant compatibility as well, nevertheless, MMCE is well compatible with IC2 in my modpack.

**Comment by NordicGamerFE** [comment]
I made a new modpack with only MMCE, CT, IC2, And JEI and still i cant add IC2 machines to structures 
![image](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/assets/18188155/22d0012f-ab42-460f-8079-6861071279e4)
image below is same exact structure config using MM
![image](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/assets/18188155/d9c18156-27c2-4a6f-927c-93d02e6e3a51)
