### ISSUE TITLE
Impetus Crash

### ISSUE THREAD

**Issue by sainagh** [NovaEngineering-Source/ModularMachinery-Community-Edition#67]
This does not happen every time, but impetus hatches seem to be having some problems causing crashes.

[crash-2024-01-08_05.51.44-server.txt](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/13861350/crash-2024-01-08_05.51.44-server.txt)

**Comment by KELETU66666** [comment]
let me see...

**Comment by KasumiNova** [comment]
Try update thaumicaugmentation.

**Comment by jchung01** [comment]
Looks like ThaumicAugmentation-1.12.2-2.1.11 is the latest and is what's present in the crash report. Could it be possible that `deregisterRenderableImpetusNode()` can be called twice, once in `invalidate()` [here](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/blob/master/src/main/java/kport/modularmagic/common/tile/TileImpetusComponent.java#L88) and again in `onChunkUnload()` [here](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/blob/master/src/main/java/kport/modularmagic/common/tile/TileImpetusComponent.java#L114C35-L114C66)? This would mean on the second call `remove()` is called on the [default immutable map](https://github.com/TheCodex6824/ThaumicAugmentation/blob/master/src/main/java/thecodex6824/thaumicaugmentation/api/client/ImpetusRenderingManager.java#L54) and thus throw the `java.lang.UnsupportedOperationException`.
