### ISSUE TITLE
[SUGGESTION] Not Consumed Inputs

### ISSUE THREAD

**Issue by Artiwolfdev** [NovaEngineering-Source/ModularMachinery-Community-Edition#83]
this is a simple but but nice addition
Not consumed Inputs so u can used the same "catalyst"  item for Ever

**Comment by TheTzdDark** [comment]
If I'm not mistaken, then there is already such an opportunity in fashion.

"setChance(0)" on the input item has this effect. For example:
`.addItemInput(<minecraft:bedrock>).setChance(0)`
