### ISSUE TITLE
ME Crafting Input Buffer

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#84]
GTNH has a bus where templates for auto craft are placed. The bus itself has an internal buffer that the multiblock sees. In fact, we combine the input bus and the ME interface in one block.

In addition, if you add such a block, it will not be superfluous to add support for AE2FC for multiblocks with liquid autocraft.

![image](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/assets/79448439/fb1976d6-7b5f-4dd6-baeb-ef8703e8a359)

**Comment by KasumiNova** [comment]
Closed as completed in 2.0.0-pre4.
