### ISSUE TITLE
CME in the GUI ME Machinery Patter Provider

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#85]
When we launch autocraft and enter ME Machinery Patter Provider, a Concurrent Modification Exception crashes

[crash-2024-04-30_22.46.53-client.txt](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/15168979/crash-2024-04-30_22.46.53-client.txt)

**Comment by KasumiNova** [comment]
How many times did it recur?

**Comment by TheTzdDark** [comment]
Many times. The crash does not happen immediately, sometimes it happens immediately after the gui is opened, and sometimes you have to wait. 

The main condition is that there is an active autocraft and the item cache is updated.

**Comment by KasumiNova** [comment]
try latest action build...
