### ISSUE TITLE
Clearing the cache of items in ME Machinery Pattern Provider

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#86]
When the server raised on the Mohist core is turned off, the cache of items in the ME Pattern Provider is cleared.

We tried to repeat the problem in a single-player game, as well as on a server raised in the development environment, but there is no bug there.

Unfortunately, we do not have the opportunity to change Mohist to something else, so we would like to fix this problem.

P.S. We also tried to understand the reason for this bug, but the only thing we understood is that when the server is turned off, an empty NBT tag of the item cache is written. I apologize for the screenshot, it's just that I didn't personally deal with the specific issue of this error.
![image](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/assets/79448439/9a6ef797-f201-446f-9f24-517ff52d15a3)

**Comment by KasumiNova** [comment]
does catserver can reproduce this problem?

**Comment by KasumiNova** [comment]
![图片](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/assets/48862050/ad390354-59b8-4919-9562-33ad9acbab0a)
Normally, it shouldn't have this problem.
Do you still keep logs related to the server?

**Comment by TheTzdDark** [comment]
> does catserver can reproduce this problem?

Yes, I have raised a small server on CatServer and the bug is present.

> Do you still keep logs related to the server?

Yes, we still keep logs.

**Comment by KasumiNova** [comment]
provide log?

**Comment by TheTzdDark** [comment]
Logs from the server to the CatServer:
[2024-05-05-1.log](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/15210736/2024-05-05-1.log)

P.S. The latest version with GItActions was used, the bug remained.

**Comment by KasumiNova** [comment]
Can't reproduce it... Tested both in single-player / ForgeServer / CatServer, but still can't get this cache flush to occur.

**Comment by TheTzdDark** [comment]
To be honest, I don't know how else to help with repeating the bug, except that I can throw off the full server build on CatServer, where the bug was reproduced.

[Server.zip](https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/files/15228934/Server.zip)

**Comment by TheTzdDark** [comment]
A small addition. I tested the bug on the latest version with Git Action, now the cache is not completely cleared, but a small number of items remain, and not necessarily all of them. The number also remains random.

**Comment by KasumiNova** [comment]
There may be some new developments... Testing the latest Actions?

**Comment by TheTzdDark** [comment]
Great! In the latest version with Git Action, there is no such error, after restarting the server, the entire cache of items is saved.

But... A new problem has arisen related to the gui of this block. For some reason, it is now impossible to interact with items from the player's inventory and with templates inside the provider itself. Because of this, I had to put the template in a block using pipes to check the main theme of this issue.

**Comment by KasumiNova** [comment]
Due to the limitations of the original Minecraft, items with more than 127 quantities have problems being serialized...

**Comment by KasumiNova** [comment]
> Great! In the latest version with Git Action, there is no such error, after restarting the server, the entire cache of items is saved.
> 
> But... A new problem has arisen related to the gui of this block. For some reason, it is now impossible to interact with items from the player's inventory and with templates inside the provider itself. Because of this, I had to put the template in a block using pipes to check the main theme of this issue.

Are there relevant reproduction steps and videos (and versions of the relevant mods)?

**Comment by TheTzdDark** [comment]
Oh, I've been away a long time. In the latest build with Git Action, everything works fine and there are no problems. Thanks!
