### ISSUE TITLE
Cannot install a GeckoLib model via a ControllerModelGetEvent.

### ISSUE THREAD

**Issue by TheTzdDark** [NovaEngineering-Source/ModularMachinery-Community-Edition#92]
When I install another model via event.modelName = "name", the model does not change.

Most likely, the problem is that this condition is incorrect, it cannot be fulfilled with the correct model name:
https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/blob/946b21708ff4de24e93c4488beca34e3e1f8518a/src/main/java/hellfirepvp/modularmachinery/common/tiles/base/TileMultiblockMachineController.java#L1318

**Comment by KasumiNova** [comment]
Is the model registered?

**Comment by TheTzdDark** [comment]
> Is the model registered?

Yes, all the models I used were pre-registered via "GeoMachineModel.registerGeoMachineModel".

**Comment by TheTzdDark** [comment]
It still seems to me that this condition, which I noted above, should look something like this:
`modelName != null && !modelName.isEmpty()`

After all, it is not logical to try to get a model by an empty name or a null one.

**Comment by KasumiNova** [comment]
https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition/blob/946b21708ff4de24e93c4488beca34e3e1f8518a/src/main/java/hellfirepvp/modularmachinery/common/tiles/base/TileMultiblockMachineController.java#L1329-L1332
The machine will first get the model via an event... It only goes back to get the default model if it returns an empty name.

**Comment by KasumiNova** [comment]
holy shit... it will be fixed in pre6.
